# Generated by Django 5.2.8 on 2025-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author'], name='analytics_b_author__4e9d47_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='analytics_b_created_812a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'created_at'], name='analytics_b_author__43b6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country'], name='analytics_u_country_d97d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='analytics_u_usernam_ddd2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['blog'], name='analytics_v_blog_id_cd4587_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['user'], name='analytics_v_user_id_a8d22a_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['blog', 'timestamp'], name='analytics_v_blog_id_879865_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['timestamp', 'blog'], name='analytics_v_timesta_c4bea4_idx'),
        ),
    ]
