# Generated by Django 5.2.8 on 2025-12-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('query_params', models.JSONField(default=dict)),
                ('execution_time', models.FloatField()),
                ('result_count', models.PositiveIntegerField()),
                ('cache_hit', models.BooleanField(default=False)),
                ('optimized', models.BooleanField(default=False)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('db_queries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='analytics_q_endpoin_358cb5_idx'), models.Index(fields=['execution_time'], name='analytics_q_executi_e3f171_idx'), models.Index(fields=['cache_hit'], name='analytics_q_cache_h_fe217b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_blogs', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.user')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_type', 'date'], name='analytics_a_snapsho_23edf1_idx'), models.Index(fields=['country', 'snapshot_type'], name='analytics_a_country_89a6e0_idx'), models.Index(fields=['user', 'snapshot_type'], name='analytics_a_user_id_96f7af_idx'), models.Index(fields=['date'], name='analytics_a_date_ca2b97_idx')],
                'unique_together': {('snapshot_type', 'date', 'country', 'user')},
            },
        ),
    ]
